### PR TITLE
Added missing FontAwesome

### PR DESCRIPTION
**Pull request by pazzoone**
Please add this missing font. Issues #212

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks

**Comment by phofmann-trust** [comment]
Any plans for a new minor release including this change? The error message in the browser console is annoying. :wink:

**Comment by barryvdh** [comment]
Pushed `v1.10.5` :)

**Comment by phofmann-trust** [comment]
Awesome, thank you! :+1: 

This closes #207 and #212.

**Pull request merged**
