### PR TITLE
Documented a guzzle subscriber which uses collectors to send data to debugbar

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by barryvdh** [comment]
Perhaps it would be be better to create and 'Third party' section and just link to the github project.

**Comment by hannesvdvreken** [comment]
On central readme or also in documentation? I'll have a look later this evening.

**Comment by barryvdh** [comment]
I would say probably also in the readme (a link below framework integrations) and the docs section. Don't know if there are any more collectors yet.

**Comment by hannesvdvreken** [comment]
Going to close this for now.

**Pull request closed without merging**
