### PR TITLE
UI refinements toolbar

### PR DESCRIPTION
**Pull request by nckrtl**
This PR add come UI refinements to the toolbar:
- Better readability of the counter in the tabs by making the background black on selection
- Better vertical alignment of the counter
- The tooltip now resizes based on the text thanks to white-space no wrap. This solves the big "padding" on the sides
- Adjusted background positioning of the logo using `center` value instead of arbitrary values. This change make it seem the logo got replace but that isn't the case
- Tooltips are better readabile when displayed in front of text on the page by apply a backdrop blur

Tested these changes in Safari, Chrome and Firefox.

ui-refinements

### CODE REVIEW

**Comment by barryvdh** [comment]
Why did you change the border-radius of the badge?

**Comment by barryvdh** [comment]
Hmm I think we can keep the old one for now.

**Comment by barryvdh** [comment]
Hmm I think the #000 might be a bit 'sharp'. What do you think of #555 as active badge color
image

**Comment by nckrtl** [comment]
Yeah that'll work as well, still high enough contrast.

**Pull request merged**
