### PR TITLE
Remove Predis object limited

### PR DESCRIPTION
**Pull request by Except10n**

### CODE REVIEW

**Comment by barryvdh** [comment]
Does this need anymore changes?

**Comment by lagun4ik** [comment]
@barryvdh Yes

**Comment by barryvdh** [comment]
what do you mean with 'yes'? What changes does it need.

**Comment by GrahamCampbell** [comment]
Surely, the phpdoc is now incorrect?

**Comment by lagun4ik** [comment]
These are all the necessary changes. The used methods are present in phpredis and predis.

**Pull request merged**
