### PR TITLE
Namespace font awesome

### PR DESCRIPTION
**Pull request by nickcolley**

### CODE REVIEW

**Comment by barryvdh** [comment]
Did you also upgrade to the latest font-awesome?

And should we also namespace the font itself? Otherwise we still get conflicts, right?

**Comment by nickcolley** [comment]
Good shout Barry :dancer: 

I've updated the namespace script to update the font-face name too now.

Also updated to font awesome 4.4.0

Can you test this out for me? I don't have this project running on my machine, happy to make amends if anything's not working.

Cheers mate.

**Comment by nickcolley** [comment]
@barryvdh is this good to go?

**Comment by barryvdh** [comment]
@maximebf this good? Haven't test this, but seems like good idea.

**Comment by barryvdh** [comment]
Gonna try how this works out..

**Comment by barryvdh** [comment]
Fixed some widgets; https://github.com/maximebf/php-debugbar/commit/c6c6ae20e1f67dc8e7a9d0f81f4cc0ebab0724b8
And used a PHP script instead of sh; https://github.com/maximebf/php-debugbar/commit/54bd5aeeb8b912c138a387113d08cf742d5f958e
Also updated to FA 4.5

Does this work for you?

**Comment by nickcolley** [comment]
Much better, that's great. Thanks!

**Pull request merged**
