### PR TITLE
Fix for wrong namespace lookup. No clean use possible otherwise.

### PR DESCRIPTION
**Pull request by clickalicious**
This fixes a bug - when extending the DataFormatter its not possible to set the new class as data formatter via collectorInstance->setDataFormatter(...) - it complains about wrong Interface.

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you use 'use DebugBar\DataFormatter\DataFormatterInterface;` instead?

**Comment by GrahamCampbell** [comment]
Yeh, it would definitely be the best idea to just import it.

**Comment by clickalicious** [comment]
Yeh, changed to your recommendation. bit late yesterday :D Seems cleaner.

**Comment by barryvdh** [comment]
Thanks!

**Pull request merged**
