### PR TITLE
Support for Symfony 4

### PR DESCRIPTION
**Pull request by Nyholm**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by kornrunner** [comment]
Any chance of merging this in and tagging a release? Thanks!

**Comment by barryvdh** [comment]
Tagged `v1.15.0`

**Comment by Cyrille37** [comment]
Hi. Could U please add "Symfony" to the README.md at "Integrations with other frameworks" section please ?

**Comment by barryvdh** [comment]
Is there a pull request?

**Comment by Cyrille37** [comment]
heu... no. I just ask because I saw this PR and did not see Symfony in the README.md.
But I can do one if U want ;-)

**Comment by barryvdh** [comment]
Sure

**Comment by Cyrille37** [comment]
Forget my request, I've just read this PR's code and it's not a Symfony PhpDebugBar support but a PhpDebugBar Symfony requirement. Sorry for the noise.

**Pull request merged**
