### PR TITLE
Close #51 - Update front-end dependencies

### LINKED ISSUE #51: Update dependencies
Could this project's front-end dependencies be updated ? Particularly the FontAwesome set which – in the version in use – uses generic class names that clash with applications the debug bar is installed on. 

Ideally I think this project's dependencies should be managed by [Bower](http://bower.io) in order for them to be kept up to date.

The same thing can be said about the jQuery dependency that is now more than two years (!!) old.

### PR DESCRIPTION
**Pull request by Anahkiasen**
This moves managing of the front-end assets to Bower and update the existing dependencies to avoid icon conflicts.

### CODE REVIEW

**Comment by glensc** [comment]
how does this exactly work?

what invokes population of `src/DebugBar/Resources/vendor` during composer install?

**Comment by barryvdh** [comment]
That folder is populated with `bower install`. The result is committed to the git repo, so no need to do anything during composer install.

**Comment by glensc** [comment]
so .bowerrc and bower.json can be added to export-ignore in .gitattributes?

**Comment by barryvdh** [comment]
Yes

**Pull request merged**
