### PR TITLE
Removed redundant calls to $this->template in TraceableTwigTemplate

### PR DESCRIPTION
**Pull request by OhMyMndy**
Removed redundant calls (they are catched by `__call`) to `$this->template` in `TraceableTwigTemplate` to remove the following incompatibility warning:

`Declaration of DebugBar\Bridge\Twig\TraceableTwigTemplate::hasBlock() should be compatible with Twig_Template::hasBlock($name, array $context = NULL, array $blocks = Array)`

### CODE REVIEW

**Comment by barryvdh** [comment]
Doesn't this fail the interface implementation?

**Comment by Mandy91** [comment]
Fortunately not see the [interface for 1.x](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/TemplateInterface.php)
Version 2.x does not have that interface and has an [abstract class instead](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Template.php) )

**Comment by Mandy91** [comment]
Can someone rerun the checks, because the checks failed on PHP 5.3 and PHP 5.4 which have been removed from Travis recently.

**Comment by barryvdh** [comment]
Closing as inactive, the Twig stuff has changed a lot.

**Pull request closed without merging**
