### PR TITLE
Add body message to mail

### PR DESCRIPTION
**Pull request by Jonathanm10**
I'd like to have the body but also to be able to interpret HTML. To have a better look at what the user will received.
Here's an example
image

Let me know if you think this should be done in an other way.

Cheers,

Jonathan

### CODE REVIEW

**Comment by jeanmonod** [comment]
This is a really nice feature! Can we have it merged? please 🙏

**Comment by barryvdh** [comment]
This will probably make it a lot slower to render. And I don't know if any styling etc would be able to leak through to the webpage.
It should be optional at least.

**Comment by angeljqv** [comment]
> any styling etc would be able to leak through to the webpage

maybe using an iframe to avoid css collisions

**Comment by barryvdh** [comment]
I think it would be cool to open the body as a popup?

**Comment by parallels999** [comment]
Fixed on #617

**Pull request closed without merging**
