### PR TITLE
PHPDoc Fixes

### PR DESCRIPTION
**Pull request by Pachonk**
I added phpdocs on many functions that had none, and fixed some of the incorrect phpdocs.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This absolutely needs squashing to one commit!

**Comment by barryvdh** [comment]
Good job. Can you squash to 1 commit as @GrahamCampbell suggested?

**Comment by GrahamCampbell** [comment]
Did you forget to force push?

**Comment by GrahamCampbell** [comment]
Now there are even more commits.

**Comment by Pachonk** [comment]
Sorry, it was my first squash. I pulled to merge instead of force pushing.

**Comment by barryvdh** [comment]
Thanks!

**Pull request merged**
