### PR TITLE
Added php7 throwable compatability #264

### PR DESCRIPTION
**Pull request by jamiehd**
I've put an exception phpdoc hint in there too so PHP5 users can still make use of it.

### CODE REVIEW

**Comment by barryvdh** [comment]
Hmm, this is good but the problem now is that we will break BC, so this would warrant a new release for just this.. See https://3v4l.org/bUWPp

An alternative would be the create a new collector, but that aint pretty either.
(So deprecate the ExceptionsCollector, create a new ThrowableCollector)

**Comment by GrahamCampbell** [comment]
This shoulodn't be needed?

**Comment by GrahamCampbell** [comment]
Just transform it like laravel does.

**Comment by barryvdh** [comment]
what does Laravel do? Convert to plain exception, with throwable as previous?

**Comment by GrahamCampbell** [comment]
Uses the symfony stuff.

**Comment by GrahamCampbell** [comment]
That's why it's exception handler has kept the Exception typehint.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Engines/PhpEngine.php#L41-L47

**Comment by barryvdh** [comment]
Okay yeah, so that would need to happen in application implementing debugbar, not much I can do about that. (Except for laravel-debugbar of course)

**Comment by jamiehd** [comment]
Well that works for me - I'm only using it in Laravel anyway. People who are using it directly can come up with their own solutions for now I suoppose. Will probably be worth releasing this as a new version in the future for people who are using their own implementations though.

**Comment by GrahamCampbell** [comment]
> so that would need to happen in application implementing debugbar

yes

**Comment by jamiehd** [comment]
I've had a look into this and it seems that due to the nested exceptions in getPrevious() this is a bit harder to implement. It's not enough to just convert the main exception - it needs to somehow go through all of the previous exceptions and check for anything that doesn't implement Exception, but I can't work out a way of doing this in the Laravel package without recreating the whole chain of exceptions.

I found I could get it to work by changing both LaravelDebugbar@modifyResponse and ExceptionsCollector@addException, but that would require both packages to be updated and also makes the symfony bits a dependency.

_LaravelDebugbar@modifyResponse_

        if (isset($response->exception)) {

            if($response->exception instanceof Exception) {

                $this->addException($response->exception);

            } else {

                $this->addException(new FatalThrowableError($response->exception));

            }

        }



_ExceptionsCollector@addException_


        if ($this->chainExceptions && $previous = $e->getPrevious()) {

            if($previous instanceof Exception) {

                $this->addException($previous);

            } else {

                $this->addException(new FatalThrowableError($previous));

            }

        }

If someone can suggest a different way for me to approach this I'm happy to spend a bit of time playing around.

**Comment by GrahamCampbell** [comment]
> I've had a look into this and it seems that due to the nested exceptions in getPrevious() this is a bit harder to implement.

This was already fixed in symfony. I fixed it myself actually. What version are you using?

**Comment by jamiehd** [comment]
Well I was only creating a new FatalThrowableError if $response->exception wasn't inherited from Exception, which meant that if the top level exception was ok, but one of the previous wasn't then it would throw an error.

I've just tried removing the check and having it create a FatalThrowableError every time and this does fix it, but it doesn't feel right to be using it in cases where a standard exception is thrown. Do you think it's acceptable as a fix to just create it every time or should I check if any of the previous are not an exception?

**Pull request closed without merging**
