### PR TITLE
Show caller in Propel tab

### PR DESCRIPTION
**Pull request by gisostallenberg**
Shows something like:
image
In the Propel tab

### CODE REVIEW

**Comment by barryvdh** [comment]
Probably good to standardise this in the QueryCollector. I'm doing something similar here: https://github.com/barryvdh/laravel-debugbar/blob/7668d62768cbd6b9f9ab8eebb11d6647869d5195/src/DataCollector/QueryCollector.php#L200-L232
But there I'm misusing the existing `stmt_id` key.

**Comment by barryvdh** [comment]
This is what it looks like for me: 
Example

**Comment by gisostallenberg** [comment]
@barryvdh QueryCollector is not in this repo. Should I add for instance ORMCollector and extend DoctrineCollector, Propel2Collector and PropelCollector from it? I have no easy means of checking DoctrineCollector and Propel2Collector though.
Skipping the various items in the backtrace is very specific to Propel.

**Comment by gisostallenberg** [comment]
@barryvdh can you answer the questions above? I think this addition is very valuable, so I hope we can craft it in a way that suits both you and me.

**Comment by barryvdh** [comment]
I think we should probaby create a AbstractQueryCollector with some useful methods, and extend from that.

**Comment by gisostallenberg** [comment]
Ok, I will add an abstract layer like that, but I'm not able to generate proper implementations for DoctrineCollector, Propel2Collector which I will default to 'first call not in the debugbar trace'

**Comment by gisostallenberg** [comment]
@barryvdh can you confirm that when I will add a change for Propel you will be able to add DoctrineCollector or Propel2Collector?

**Pull request closed without merging**
